version: "2.2"
services:
  web:
    build: 
      context: .
      dockerfile: node.Dockerfile
    restart: always
    ports: 
      - "8020:8020"
    depends_on:
      - mysql-server
      - psql-server
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"
    depends_on:
      - mysql-server
      - psql-server
  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    volumes:
      - mysql-data:/var/lib/mysql
  psql-server:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: mypass
    ports:
      - "5000:80"
volumes:
  mysql-data: